name: build

on: [push, pull_request]
env:
  BUILD_TYPE: Release

jobs:
  ubuntu-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: cmake build
        run: |
          mkdir -p dist
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
